version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/phishbusters-api
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ec2-user
