version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGODB_URI=mongodb://db:27017/mydb
  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
